### PR TITLE
Lint & remove magic strings

### PR DESCRIPTION
**Pull request by Bjohnson131**
Hello, I've done 3 things in this PR.

1: I ran `cargo fmt`, as well as `cargo clippy --fix`
2: I removed the repeated strings for the half-second-tick and two-second-tick, and replaced all instances with a constant
3: I organized the bevvy registry into logical chunks. 

Hopefully these changes are welcome, let me know if I should change anything :)

### CODE REVIEW

**Comment by ryankopf** [comment]
I do wonder if the enums really need a new line for each item. I suppose if we start to alphabetize them, that would make that look better. (Example the enum PlantType).

I do think the linter did a bad job in start_game_ui doing the buttons.

I don't think I'm a fan of removing mod_use and having to specify the module for each of the functions. While it could be argued we clutter up the namespace, it's looking like each module will only have 3 or 4 functions in it, which currently look like they can be kept uniquely named.

I don't know the current community consensus on line-breaks in lists of strings, such as the names vec! under namegiving_system. I feel like modern IDEs have text wrapping if necessary.

The rest of it seems great.

Thoughts?

**Comment by Bjohnson131** [comment]
Hey @ryankopf, I agree on most points here.

> I do wonder if the enums really need a new line for each item. I suppose if we start to alphabetize them, that would make that look better. (Example the enum PlantType).

Agreed. I'll alphabetize the enums. ✔️ 

> I do think the linter did a bad job in start_game_ui doing the buttons.

Yes. it seems that it kept the comments, and inlined the rest.. Does the comment need to stay there? if not, I'll remove it, and re-lint.

> I don't think I'm a fan of removing mod_use and having to specify the module for each of the functions. While it could be argued we clutter up the namespace, it's looking like each module will only have 3 or 4 functions in it, which currently look like they can be kept uniquely named.

The reason I did this is so that I could navigate the files easier thru my IDE, as intellij / clion does not process macros in the files. I can revert this.

> I don't know the current community consensus on line-breaks in lists of strings, such as the names vec! under namegiving_system. I feel like modern IDEs have text wrapping if necessary.

I'm not sure on this, either. I think that to prevent this, I'll toss in a `clippy.toml`, and/or a `rustfmt.toml`. Is that ok with you?

**Comment by ryankopf** [comment]
Sounds good.
As for the buttons, no the comments don't necessarily need to stay.

**Comment by Bjohnson131** [comment]
Apologies for taking so long, I'll update this PR tonight or tomorrow.

**Comment by Bjohnson131** [comment]
Alright, the changes have been made

**Comment by ryankopf** [comment]
Most recent changes chomped a bunch of things poorly. I think when we changed the settings for the line breaks for enums and vecs of strings, it's been changed for everything. For example now all the function definitions are one-lined instead of being broken into multiple lines.

A good example is click.rs, where this was mushed into one single line:

app.add_event::<ObjectFinderEvent>().add_system_set(SystemSet::on_update(GameState::InGame).with_system(mouse_click_input)).add_system_set(SystemSet::on_update(GameState::InGame).with_system(mouse_drag_system)).add_system_set(SystemSet::on_update(GameState::InGame).with_system(object_finder_system)).add_system(mouse_move_system).insert_resource(Dragging { ..default() });

To clarify when I was asking about the line-breaks, I only meant specifically for lists of strings, like in the names vec!. Realistically the names should be in a loadable data file anyway.

I'm going to close this PR and update contributing notes. I'd like to request each PR focus on one thing. Removing magic strings should be separate from linting and formatting.

**Pull request closed without merging**
